- jd_nianCollect.j
> 迁移炸年兽集爆竹脚本

- .github/workflows/deploy_tencent_scf.yml
> 云函数新增京东炸年兽互助码secret

- serverless.yml
> 云函数新增炸年兽task、集爆竹

- jd_jxnc.js
[京喜农场]
变更 答题选项顺序由 ABCD 改为 DCBA （成功率更高）
变更 APP种子未提供 token 提醒级别变更为 2
> [京喜农场] 变更 答题选项顺序由 ABCD 改为 DCBA （成功率更高）& APP种子未提供 token 提醒级别变更为 2

- githubAction.md
> 优化githubAction.md阅读体验

- serverless.yml
> 云函数除去京东家庭，减少黑号风险

- serverless.yml
> 云函数新增京东神仙书院

- .github/workflows/deploy_tencent_scf.yml
> 云函数增加京东神仙书院地理位置secret

- serverless.yml
> 云函数新增集鞭炮赢京豆

- serverless.yml
> 云函数新增京东炸年兽签到任务

- serverless.yml
> fix 字符过长导致云函数部署失败的问题

- update_task.sh
> Loon task 清单中，去除有注释但没有task的内容

- serverless.yml
> 云函数新增京东炸年兽AR

- update_task.sh
1. QX Rewrite清单带上注释；2. QX Task 尝试修复多换行符的问题。
> 1. 增加Surge task尾部内容；2. 尝试修复QX task换行问题

- serverless.yml
> 云函数新增京东炸年兽小程序

- .github/workflows/deploy_tencent_scf.yml
> 云函数新增京东炸年兽小程序secret

- githubAction.md
> 新增京东炸年兽小程序环境变量说明

- serverless.yml
> fix 字符过长可能导致的云函数部署失败

- .github/workflows/deploy_tencent_scf.yml
云函数新增宠汪汪赛跑通知和东东超市是否参加作者PK队伍的secret、取消818的secret
> 云函数新增宠汪汪赛跑通知和东东超市是否参加作者PK队伍的secret、取消818的secret

- docker/Readme.md
> 增加远程任务列表挂载说明

- serverless.yml
> 云函数调整东东小窝运行时间

- githubAction.md
> 增加JXNC_SHARECODES详细说明

- jd_jxnc.js
[京喜农场] 
修复 助力码 JSON 格式检测错误
变更 兼容 ret=1032 助力 APP 专属种子 (可继续助力，直到助力到达上限 或 内置助力完毕 或 随机助力到达最大限制次数)
> [京喜农场] 修复 助力码 JSON 格式检测错误 & 变更 兼容 ret=1032 助力 APP 专属种子

- .github/workflows/update_list.yml
- README.md
- docker/crontab_list.sh
- update_list.sh
自动生成首页Readme中的脚本文件清单，无需再人工修改，请勿删除Readme中隐藏状态的标记行。
> 自动生成首页Readme中的脚本文件清单，无需再人工修改，请勿删除Readme中隐藏状态的标记行。

- serverless.yml
> 云函数新增闪购盲盒、调整京东汽车Cron

- githubAction.md
- jd_firecrackers.js
[集鞭炮赢京豆]
新增 满足兑换 FIRECRACKERS_NOTITY_BEAN 个京豆时进行 notify 通知
新增 黑号自动跳过任务执行
环境变量说明：
`FIRECRACKERS_NOTITY_BEAN`  满足兑换 X 个京豆通知开关     | 非必须 |  默认 0 不通知，输入 120 表示满足兑换 120 个京豆时通知 
通知样例
```
集鞭炮赢京豆
【京东账号1】狗东看刀
【鞭炮🧨】本次获得 0，共计441
【京豆】请手动兑换 5 个京豆，需消耗花费🧨 200
```
> [集鞭炮赢京豆] 跳过黑号任务 & 增加兑换 x 京豆通知（通过环境变量控制）

- jd_firecrackers.js
> [集鞭炮赢京豆] 修复运算符错误

- .github/workflows/deploy_tencent_scf.yml
> 云函数新增闪购盲盒secret

- serverless.yml
> 云函数新增京东神仙书院答题
